### ISSUE TITLE
refresh timer does not work

### ISSUE THREAD

**Issue by tbroll** [aprsworld/overlayOnImage#1]
Refresh timer does not do anything right now. Earlier today, I did have it where I could get some output but it crashed on me due to overflow. So, I removed its functionality so that it would not interrupt other things that I was working on.

**Comment by tbroll** [comment]
Now, I have it where the refresh interval will change a console.log to the console but I have not gotten it to update the json data. My goal with the refresh interval is to first isolate the imported json data spans from the user created spans. Then, I only want to change the data that came from the json file not the added text that the user can choose to add to give the data more meaning.

**Comment by kb0thn** [comment]
use IDs on your spans and this is trivial. See:
http://data.asrichards.com/data/current.php?nonav=1&station_id=A4221
for an easy example

On 7/23/2015 2:10 PM, tbroll11 wrote:

> Now, I have it where the refresh interval will change a console.log to
> the console but I have not gotten it to update the json data. My goal
> with the refresh interval is to first isolate the imported json data
> spans from the user created spans. Then, I only want to change the data
> that came from the json file not the added text that the user can choose
> to add to give the data more meaning.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/overlayOnImage/issues/1#issuecomment-124214369.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com
